# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 00:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('createdate', models.DateTimeField(auto_now=True, verbose_name='bankcreatedate')),
            ],
        ),
        migrations.CreateModel(
            name='CustsomerManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('managerid', models.CharField(max_length=6)),
                ('managerbank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Zmfen.Bank')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ZmOpenId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=20)),
                ('certno', models.CharField(max_length=20)),
                ('createdate', models.DateTimeField(auto_now=True, verbose_name='openidcreatedate')),
            ],
        ),
        migrations.CreateModel(
            name='ZmScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=30)),
                ('certno', models.CharField(max_length=20)),
                ('score', models.IntegerField()),
                ('createdate', models.DateTimeField(auto_now=True, verbose_name='scorecreatedate')),
                ('managerid', models.ManyToManyField(to='Zmfen.CustsomerManager')),
            ],
        ),
    ]
