# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 06:38
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('Zmfen', '0002_zmscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('createdata', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CustsomManager',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('managerid', models.CharField(max_length=5)),
                ('managerbank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Zmfen.Bank')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ZmOpenId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=20)),
                ('certno', models.CharField(max_length=20)),
                ('createdata', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='zmscore',
            name='uuidfield',
        ),
        migrations.AddField(
            model_name='zmscore',
            name='managerid',
            field=models.ManyToManyField(to='Zmfen.CustsomManager'),
        ),
    ]
